In [5]:
import numpy as np
import torch
from torch import nn

In [94]:
# Dropout
m = nn.Dropout(p=0.2)
input = torch.randn(2000, 1600)
output = m(input)
input.shape, (input == 0).sum(), (output == 0).sum() / output.numel()

(torch.Size([2000, 1600]), tensor(0), tensor(0.2003))

In [97]:
# Linear
x = torch.rand((5, 10, 7))
l = nn.Linear(7, 8)
y = l(x)
y.shape

torch.Size([5, 10, 8])

In [100]:
# Softmax
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
print(input)
print(output)
print(output.sum(1, keepdim=True))

tensor([[-0.2459,  0.3107, -0.1120],
        [ 0.6032,  0.1166,  1.6144]])
tensor([[0.2572, 0.4487, 0.2941],
        [0.2292, 0.1409, 0.6300]])
tensor([[1.],
        [1.]])


In [103]:
# PatchEmbedding
image_size = 224, 224
patch_size = 16
embed_dim = 192
channels = 3
grid_size = image_size[0] // patch_size, image_size[1] // patch_size
num_patches = grid_size[0] * grid_size[1]
proj = nn.Conv2d(channels, embed_dim, kernel_size=patch_size, stride=patch_size)

im = torch.rand((8, 3, *image_size))
B, C, H, W = im.shape
print(f'B = {B}. C = {C}. H = {H}. W = {W}')
x = proj(im)
print(x.shape)
x = x.flatten(2).transpose(1, 2)
print(x.shape)
print(proj.weight.shape, proj.weight.numel(), proj.bias.shape)

B = 8. C = 3. H = 224. W = 224
torch.Size([8, 192, 14, 14])
torch.Size([8, 196, 192])
torch.Size([192, 3, 16, 16]) 147456 torch.Size([192])


In [108]:
# linspace
torch.linspace(0, 0.1, 12)

tensor([0.0000, 0.0091, 0.0182, 0.0273, 0.0364, 0.0455, 0.0545, 0.0636, 0.0727,
        0.0818, 0.0909, 0.1000])

In [4]:
# LayerNorm
N, C, H, W = 20, 5, 10, 10
input = torch.randn(N, C, H, W)
input = torch.permute(input, (0, 2, 3, 1))
layer_norm = nn.LayerNorm([H, W, C])
output = layer_norm(input)
print(input.shape, output.shape)
print(layer_norm.weight.shape, layer_norm.bias.shape)

torch.Size([20, 10, 10, 5]) torch.Size([20, 10, 10, 5])
torch.Size([10, 10, 5]) torch.Size([10, 10, 5])


In [9]:
# Numpy to Torch by stack and concatenate
a = [
    np.random.rand(4, 4, 2),
    np.random.rand(4, 4, 2),
    np.random.rand(4, 4, 2),
]
t1 = torch.zeros((3, 4, 4, 2))
t1[0] = a[0]
t1[1] = a[1]
t1[2] = a[2]
print(t1.dtype, t1.shape)
t2 = torch.zeros((12, 4, 4, 2))
t2[:4] = a[0]
t2[4:8] = a[1]
t2[8:] = a[2]
print(t2.dtype, t2.shape)

TypeError: can't assign a numpy.ndarray to a torch.FloatTensor

In [16]:
t = torch.rand(2, 3)
print(t.shape)
torch.unsqueeze(t, 0).shape, t.dim() == 2

torch.Size([2, 3])


(torch.Size([1, 2, 3]), True)

In [19]:
t1 = torch.rand(5, 6, 2)
t2 = torch.permute(t1, (2, 0, 1))
torch.allclose(t1[..., 0], t2[0, ...]), torch.allclose(t1[..., 1], t2[0, ...]), torch.allclose(t1[..., 1], t2[1, ...])

(True, False, True)